
name: deployment

on:
  workflow_run:
    workflows: [tests]
    branches: [develop, main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      IS_CI: "True"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      #----------------------------------------------
      # Deploy the project
      #----------------------------------------------
      - name: Deploy to Staging
        id: staging-deploy
        run: |
          source .venv/bin/activate
          inv staging aws.docker-login
          inv staging image deploy --verbosity=0
        if: ${{ github.ref == 'refs/heads/develop' }}
      - name: Deploy to Production
        id: production-deploy
        run: |
          echo Implement when production is configured!
#          source .venv/bin/activate
#          inv production aws.docker-login
#          inv production image deploy --verbosity=0
        if: ${{ github.ref == 'refs/heads/main' }}
